### ISSUE TITLE
Erro handling public folder

### ISSUE THREAD

**Issue by jimmywells2** [gpailler/MegaApiClient#43]
Hi. 

I am trying to handle accessing public folders. It seem you can only handle folders with this library if they are created inside your own account by accessing them as a private node rather than a public node like:

e.g. https://mega.nz/#F!firsthash!secondhash

**Comment by gpailler** [comment]
Hello @jimmywells2. Sorry for the long delay. Could you post a link to reproduce this issue?

**Comment by Astarel** [comment]
I was faced with the same problem described by @jimmywells2. When you upload file (tried with MegaApiClient-1.2.2, C# 4.5) to the shared folder, all other accounts having access to this folder can`t read or download it using web site(or any other way). Mega web site marks this file as not decrypted.  But owner of folder which account used to upload file to shared folder can read and download file with no problem. 

But if you upload file to the not shared folder (MegaApiClient) and then manually by using web site move this file to the public folder problem not appears. All accounts that have acess to the public folder can read and download this file.

**Comment by gpailler** [comment]
@Astarel Could you try with latest version (1.3.1)? I fixed issues related to shared folders on 1.3.0.

**Comment by Astarel** [comment]
@gpailler Checked for 1.3.1, 1.3.0, 1.2.2 versions (installed by nuget). Problem still exists.

**Comment by gpailler** [comment]
Ok thanks for the recheck

**Comment by Astarel** [comment]
Need to clarify. Assume there are two mega accounts (A1 and A2). A2 creates folder and shared it with A1. If you upload file to shared folder by using MegaApiClient with A2 login Mega site will marks it as not decrypted for A1 (but it`s okay for A2) and vice versa - file uploaded by A1 works fine only when you accessing it with A1 login. No matter who owns shared folder.

**Comment by gpailler** [comment]
Thanks for the details. I identified the issue.

Repro:
- Using MegaApiClient, create a folder
- Share the folder in the WebUI with USERB
- Upload a file in the folder using same MegaApiClient instance
=> Uploaded file cannot be decrypted by USERB
The file cannot be decrypted by USERB because MegaApiClient was not aware the folder was shared and encrypt the file using personal key instead shared key.

If folder is already created and shared before uploading the file, the file is correctly decrypted on USERB side.

The Upload method should refresh the parent node before creating new node to use correct key.

_Create + Share + Upload_
![create_share_upload](https://cloud.githubusercontent.com/assets/3621529/21173239/bf46a14c-c211-11e6-8059-bd1618f5df45.gif)

_Upload only_
![upload_only](https://cloud.githubusercontent.com/assets/3621529/21173260/d0c007e2-c211-11e6-806e-dac32ef445bb.gif)

**Comment by ArchonDeveloper** [comment]
@gpailler . Hello

 It seems those two guys tells about the different issues. And I faced with both.
**_jimmywells2_** told that library doesn't give you possibility to handle public URLs. I think he meant that when anybody share folder with your. You library doesn't have power to get node list relatively to that public URL as it Mega.Nz does. It hink that would be a great enchancement in the future. 

**_Astarel_** told about writing files in shared folder. And then this files doesn't accessible via browser. He told about another scenario but I think in core it is relative with my.
I have very similar issue but with another scenario. 
1. I shared folder in Mega.nz with your library using Aaccount1. 
2. Open that link in Browser using Anonymous and everything okay. I can see what that folder contains.
3. Then I add in shared folder file1.txt with your lilbrary using Account1. And it is can be open in browser with Account1. If I open that shared folder in browser using Anonymous, only that particular file1.txt can't be decrypt but all another can.

Though when I add file using account1 into the folder in browser. And then open that file from browser then everything is okay.

About your workaround. It doesn't work for me. Because when I put file in shared folder it is already exist and shared. Could you please try to reproduce my scenario?

Thanks for your library and updates they are very useful.

**Comment by gpailler** [comment]
Thanks for the details. I will investigate.

**Comment by gpailler** [comment]
First issue is fixed on develop
About second issue. @ArchonDeveloper, I tried the following scenario and it works:

```
var root = this.context.Client.GetNodes().Single(x => x.Type == NodeType.Root);
var folder = this.context.Client.CreateFolder("Folder", root);
var file1 = this.context.Client.UploadFile("file1.txt", folder);
Uri link = this.context.Client.GetDownloadLink(folder);

// At this point, I open link and I see the share with file1 on it

// The previous folder variable contains node information before the node was shared. 
// I retrieve the node again to get a new node instance with node sharing info on it
folder = this.context.Client.GetNodes().Single(x => x.Id == folder.Id);

var file2 = this.context.Client.UploadFile("file2.txt", folder); 
```
With this code, I see both files on the share (with an anonymous account). If I don't retrieve again the node, file2.txt is marked as encrypted on the share.

Could you test this code and confirm you have same result?

**Comment by gpailler** [comment]
First issue fixed.
Workaround available for second issue
